# Generated by Django 3.2.1 on 2021-05-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210512_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccnjobcard',
            name='ccn_head_to_engg_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ccnjobcard',
            name='engg_task_complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ccnjobcard',
            name='forwareded_to_ccn_head_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
