# Generated by Django 3.2.1 on 2021-05-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210512_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccnjobcard',
            name='ccn_head_to_engg_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ccnjobcard',
            name='engg_task_complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccnjobcard',
            name='forwareded_to_ccn_head_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccnjobcard',
            name='job_on',
            field=models.CharField(blank=True, choices=[('User Head', 'User Head'), ('CCN Head', 'CCN Head'), ('Engineer', 'Engineer'), ('Cutomer', 'Cutomer')], default='User Head', max_length=10),
        ),
    ]
